### ISSUE TITLE
Phân tích đề tài web bán hàng: phụ kiện chó mèo

### ISSUE THREAD

**Issue by tuananh6195** [nguyenhoangminhhus/CNPM17-Web-ban-hang#3]
Mọi người vào đây thảo luận phân tích nào.

**Comment by nguyenhoangminhhus** [comment]
Giao diện thì chưa xét vội. Chức năng thì như thế nào nhỉ?

**Comment by thanhcongpro** [comment]
thêm sửa xóa phụ kiện chó mèo nhé :) .

**Comment by thanhcongpro** [comment]
https://www.youtube.com/watch?v=M0jdFS4ZyEk&list=PLRhlTlpDUWsyK1TIsewrQ7WwC7QkCSCPD
 làm theo mấy video này của ông này là xong 1 trang web theo mô hình MVC. thay đổi nội dung mh cần bán thôi .  t ngồi chép lại code của ông ý mất 1 tuần . muốn có 1 project hoàn chình thì có nuôn rồi. gõ lại cho nhớ thôi

**Comment by ChapDuong** [comment]
Theo như công nói thì ae lm .Net theo MVC cx dc,, rồi từ đó phát triển thêm,

**Comment by ChapDuong** [comment]
Nếu có time sẽ làm thêm mấy cái kiểu tích hợp thanh toán cổng điện tử, gmail, mạng xh, .. map..

**Comment by tuananh6195** [comment]
Nào. Phân tích cơ bản đã nào. Mục đích của website là gì?

**Comment by nguyenmanhhung12395** [comment]
website bán hàng phục vụ cho người nuôi thú cưng =)) nên chức năng chính sẽ gồm đặt hàng,quản lý thông tin khách hàng,kho hàng,thanh toán vận chuyển.Các chức năng chính như vậy đc chưa nhỉ ?

**Comment by locnb1995** [comment]
mục đích là đưa ra các mặt hàng về phụ kiện chó mèo cho khách hàng mua

**Comment by thanhcongpro** [comment]
theo t là mình làm 1 web đơn giản nhưng đầy đủ chức năng nhưng chung quy lại là 4 chức năng chính thêm, sửa. xóa , tra cứu sản phẩm . Thêm 1 số chức năng nhỏ như phản hồi đánh giá của khách hàng về sản phẩm. :)) . Làm 1 trang gọi là trang liên hệ nữa..... Có phân quyền chủ shop và khách hàng

**Comment by nguyenmanhhung12395** [comment]
t tưởng bán hàng phải gồm đặt hàng,thanh toán các kiểu chứ ?

**Comment by thanhcongpro** [comment]
nếu thế thì là dự án nhiều tiền rồi rồi :)

**Comment by thanhcongpro** [comment]
hình như đặt hàng thì người mua chỉ cần để lại thông tin về địa chỉ số điện thoại  mặt hàng muốn mua rồi lưu vào trong DB . xong chủ shop xem rồi ship nhỉ. chắc  làm đc  :))

**Comment by tuananh6195** [comment]
Đối tượng sử dụng website là những ai?

**Comment by nguyenhoangminhhus** [comment]
Đối tượng đương nhiên là người có nhu cầu r

**Comment by tuananh6195** [comment]
Đừng trả lời chung chung thế

**Comment by nguyenhoangminhhus** [comment]
Thì làm sao mà xác định được đối tượng là nhóm người dùng nào đâu ông

**Comment by locnb1995** [comment]
đúng rồi đấy ai có nhu cầu thì vào chứ giờ làm sao nói rõ được

**Comment by nguyenhoangminhhus** [comment]
Chẳng nhẽ là nhóm đối tượng nữ hay nam, già hay trẻ, sinh viên hay đã đi làm à? Nhóm đối tượng của bài này chỉ là người nuôi pet thôi

**Comment by ChapDuong** [comment]
nên xây dựng là chung cho tất ca mọi ngườinhes

**Comment by tuananh6195** [comment]
Các ông chán quá. Những đối tượng sử dụng là quản trị viên và khách hàng nhá

**Comment by ChapDuong** [comment]
ak.. cái đấy thi chả phải phân biệt thì sao mem?

**Comment by ChapDuong** [comment]
đâu hết rồi??

**Comment by tuananh6195** [comment]
Ai thống kê lại hộ phát nhỉ. mục đích, đối tượng với các chức năng chính nhỉ

**Comment by nguyenhoangminhhus** [comment]
Mục đích: website bán hàng phục vụ cho người nuôi thú cưng
Đối tượng: quản trị viên và khách hàng sử dụng
Chức năng: quản lý sản phẩm, quản lý khách hàng, đặt hàng, đánh giá
