### ISSUE TITLE
Phân tích các chức năng chính và hướng xây dựng project

### ISSUE THREAD

**Issue by nguyenhoangminhhus** [nguyenhoangminhhus/CNPM17-Web-ban-hang#6]

**Comment by tuananh6195** [comment]
Các bạn nêu các chức năng chính ra nào

**Comment by nguyenthichauhus** [comment]
cái này hôm trước Dương viết rồi,

**Comment by tuananh6195** [comment]
Dương chưa nói, cũng chưa ai đưa ra ntn

**Comment by nguyenthichauhus** [comment]
USE CASE
CLIENT
Use case 1 : Đăng ký
•	Họ tên
•	Username
•	Email
•	Password
( Tất cả các trường không được để trống)
Use case 2 : Đăng nhập
•	Username
•	Password
( Tất cả các trường không được để trống)
•	Đăng nhập bằng Google, Facebook,…
Use case 2.1 : Chức năng quên mật khẩu
•	Email
•	Username
Use case 3 : Hiển thị danh mục sản phẩm
Use case 4 : Hiển thị khuyến mãi
•	Hiển thị khuyến mãi trên từng sản phẩm
•	Hiển thị khuyến mãi chung
•	Hiển thị chi tiết khuyến mãi
Use case 5 : Hiển thị các sản phẩm nổi bật
Use case 6 : Hiển thị thông tin liên hệ
•	Địa chỉ
•	Hotline
•	Email
Use case 7 : Hiển thị danh sách sản phẩm
Use case 8 : Hiển thị chi tiết sản phẩm
•	Tên
•	Giá
•	Mô tả
•	Ảnh
•	Khuyến mãi
•	Lượt xem
•	Đánh giá người dùng
•	Mô tả chi tiết
Use case 9 : Chức năng tìm kiếm (theo từ khóa và theo danh mục)
Use case 10 : Chức năng hiển thị thông tin tài khoản
•	Họ tên
•	Số điện thoại
•	Email
•	Địa chỉ
•	Thông tin thanh toán
Use case 10.1: Chức năng đổi mật khẩu
•	Mật khẩu cũ
•	Mật khẩu mới
•	Xác nhận mật khẩu mới
Use case 11 : Chức năng quản lý thông tin cá nhân ( thêm, xóa, sửa)
•	Họ tên*
•	Số điện thoại
•	Email*
•	Địa chỉ

Use case 12 : Chức năng giỏ hàng
•	Danh sách sản phẩm đã chọn
•	Đơn giá
•	Số lượng
•	Thành Tiền
Use case 13 : Chức năng thanh toán
•	Danh sách sản phẩm đã chọn
•	Đơn giá
•	Số lượng
•	Thành Tiền
•	Mã khuyến mãi
•	Thông tin người mua 
•	Hình thức thanh toán
Use case 14 : Chức năng kiểm tra danh sách đơn hàng
•	Chưa có tài khoản hoặc chưa đăng nhập: kiểm tra bằng mã + email
•	Có tài khoản check theo email ra danh sách đơn hàng
Use case 14.1 : Kiểm tra chi tiết đơn hàng
•	Danh sách sản phẩm đã mua
•	Đơn giá
•	Số lượng
•	Thành Tiền
•	Thông tin người mua 
•	Hình thức thanh toán
•	Trạng thái (đã xác nhận đơn hàng, đang giao, hoàn thành)

Use case 15 : Chức năng hướng dẫn

**Comment by ChapDuong** [comment]
Thế phân chia như thế nào?

**Comment by ChapDuong** [comment]
CoongPlus có kinh nghiệm thực tế rồi chỉ ae nhé

**Comment by nguyenhoangminhhus** [comment]
Mọi người tải source tree về sử dụng nha

**Comment by nguyenhoangminhhus** [comment]
Ai chưa biết cách sử dụng có thể tìm hiểu trên mạng vì cái này cũng dễ sử dụng. Còn không thì có thể hỏi t

**Comment by nguyenthichauhus** [comment]
cho link đi :D

**Comment by ChapDuong** [comment]
https://www.sourcetreeapp.com/

**Comment by nguyenmanhhung12395** [comment]
Source Tree là gì vậy ô ơi

**Comment by ChapDuong** [comment]
cái để quản lý code + đẩy code lên git đó ô

**Comment by ChapDuong** [comment]
sao k dùng git desktop đó minh?

**Comment by tuananh6195** [comment]
đang thảo luận mà lại chuyển sang nói về git là sao

**Comment by ChapDuong** [comment]
thế thảo luận đi

**Comment by ChapDuong** [comment]
Coongplus , lộc ,Minh??hùng?châu?

**Comment by locnb1995** [comment]
Hôm nay là về vấn đề gì đây

**Comment by tuananh6195** [comment]
vấn đề cũ đã xong đâu

**Comment by nguyenthichauhus** [comment]
ai có kinh nghiệm,hướng dẫn mn đi từng bước đi ạ
